#!/usr/bin/env python

PACKAGE = 'transforms'
import roslib;roslib.load_manifest(PACKAGE)
import rospy

import dynamic_reconfigure.client

def callback(config):
    rospy.loginfo("Config set to {x}, {y}".format(**config))

if __name__ == "__main__":
    rospy.init_node("transform_broadcaster")

    client = dynamic_reconfigure.client.Client("transform_server", timeout=30, config_callback=callback)

    r = rospy.Rate(0.1)
    rospy.spin()
    while not rospy.is_shutdown():
        r.sleep()
